# Generated by Django 5.2.8 on 2026-01-21 05:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='color',
            field=colorfield.fields.ColorField(default='#124470', image_field=None, max_length=25, samples=None),
        ),
    ]
