# Generated by Django 5.2.8 on 2026-01-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
