# Generated by Django 5.2.8 on 2025-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_exporthistory_instructor_alter_batch_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='ref_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
