# Generated by Django 5.2.8 on 2026-01-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_instructor_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_enrollments', to='App.batch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='App.student'),
        ),
    ]
