# Generated by Django 5.2.8 on 2026-01-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_payments_ref_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('COMPLETED', 'completed'), ('DROPPED', 'dropped')], default='ACTIVE', max_length=20),
        ),
    ]
