# Generated by Django 5.2.8 on 2026-01-15 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_enrollment_batch_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payments', to='App.student'),
        ),
    ]
